# Generated by Django 5.2.3 on 2025-06-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='promotionimage',
            options={'verbose_name': 'Изображение акции', 'verbose_name_plural': 'Изображения акций'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='images',
            field=models.ManyToManyField(to='promotions.promotionimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название акции'),
        ),
        migrations.AlterField(
            model_name='promotionimage',
            name='image',
            field=models.ImageField(upload_to='promotions/', verbose_name='Изображение'),
        ),
    ]
