# Generated by Django 4.2.23 on 2025-07-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_options_alter_promotionimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='images',
        ),
        migrations.AddField(
            model_name='promotionimage',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotions.promotion', verbose_name='Акция'),
            preserve_default=False,
        ),
    ]
