# Generated by Django 4.2.23 on 2025-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
