# Generated by Django 5.2.3 on 2025-06-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона в международном формате, например +996700333111', max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
