# Generated by Django 4.2.23 on 2025-07-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmationcode',
            name='user',
        ),
    ]
