# Generated by Django 5.2.4 on 2025-07-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
        ('users', '0005_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
    ]
