# Generated by Django 4.2.23 on 2025-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Enter city, district, street, and house number', null=True, verbose_name='Address'),
        ),
    ]
