# Generated by Django 5.2.4 on 2025-07-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250704_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ', 'verbose_name_plural': 'РџРѕР»СЊР·РѕРІР°С‚РµР»Рё'},
        ),
    ]
