# Generated by Django 4.2.23 on 2025-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Введите город, район, улицу и номер дома', null=True, verbose_name='Address'),
        ),
    ]
