# Generated by Django 4.2.23 on 2025-07-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Карточка информаций', 'verbose_name_plural': 'Карточки информация'},
        ),
    ]
