# Generated by Django 4.2.23 on 2025-07-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pagecontent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона для WhatsApp')),
            ],
            options={
                'verbose_name': 'Номер для WhatsApp',
                'verbose_name_plural': 'Номера для WhatsApp',
            },
        ),
    ]
