# Generated by Django 5.2.3 on 2025-06-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='stationery',
            options={'verbose_name': 'Канцелярский товар', 'verbose_name_plural': 'Канцелярские товары'},
        ),
        migrations.AlterModelOptions(
            name='stationeryimage',
            options={'verbose_name': 'Изображение канцелярии', 'verbose_name_plural': 'Изображения канцелярии'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Вариация', 'verbose_name_plural': 'Вариации'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='images',
            field=models.ManyToManyField(to='stationery.stationeryimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='variations',
            field=models.ManyToManyField(to='stationery.variation', verbose_name='Вариации'),
        ),
        migrations.AlterField(
            model_name='stationeryimage',
            name='image',
            field=models.ImageField(upload_to='stationery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип вариации'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Изменение цены'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение вариации'),
        ),
    ]
